version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "mysecretpassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  etl:
    container_name: etl_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - ../data:/app/data
      - ./db.sql:/db.sql
      - ./etl_load_data.py:/etl_load_data.py
      - ./query1.sql:/query1.sql
      - ./query2.sql:/query2.sql
      - ./query3.sql:/query3.sql
      - ./query4.sql:/query4.sql
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
